name: Script Make ArchBlues ISO
description: A workflow to build an ArchBlues ISO image

runs:
  using: 'composite'
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: pacman -Sy --noconfirm archiso base-devel efibootmgr edk2-ovmf gnupg grub openssl qemu-desktop 
      shell: bash
    - run: mkdir -p ./Build ./out
      shell: bash
    - run: mkarchiso -v -w ./Build -o ./out ./ArchBluesProfile
      shell: bash
