name: Build ArchBlues ISO

on:
  push:
   branches: [main]
  workflow_dispatch:

jobs:
  build:
   runs-on: ubuntu-latest
   container:
     image: archlinux:latest
     options: --privileged
   steps:
     - name: Checkout 
       uses: actions/checkout@v4
     - name: Install dependencies
       run: pacman -Sy --noconfirm archiso syslinux grub xorriso dosfstools efibootmgr
       shell: bash
     - name: Build the ISO
       run: mkarchiso -v -w ./build -o ./out ./ArchBluesProfile
       shell: bash
    
